version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/spec/fixtures/test_site"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
