---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.3
before_install:
- gem install bundler -v 1.17.3
- (cd spec/fixtures/test_site && bundle install --path ../../../${BUNDLE_PATH:-vendor/bundle})
jobs:
  include:
  - env: CHECK=rspec
    script:
    - bundle exec rake
  - env: CHECK=build
    script:
    - (cd spec/fixtures/test_site && bundle exec jekyll build --strict --trace && ls -la _site)
