---
os: linux
language: ruby
cache: bundler
rvm:
  - 2.5.3
before_install: gem install bundler -v 1.17.3
jobs:
  include:
  - env: CHECK=rspec
    script:
    - bundle exec rake
  - env: CHECK=sorbet
    script:
    - bundle exec srb tc --ignore=/vendor
  - env: CHECK=build
    gemfile: spec/fixtures/test_site/Gemfile
    install:
    - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
    script:
    - (cd spec/fixtures/test_site && bundle exec jekyll build --strict --trace --verbose)
    - (cd spec/fixtures/test_site && find _site -type f && echo -e '\n===\n' && cat _site/galleries/first/index.html && file _site/galleries/second/third/Morgenspaziergang-3.jpg_thumb.jpg)
