---
os: linux
dist: focal
language: ruby
cache: bundler
rvm:
  - 2.7.1
  - 3.1.2

# adopt future bundler 3 config style
before_install:
  - bundle config set path ${BUNDLE_PATH:-vendor/bundle}
  - bundle config set jobs 3
  - bundle config set retry 3
install: bundle install

jobs:
  include:
  - env: CHECK=ruby
    script:
    - bundle exec rake
  - env: CHECK=build
    gemfile: spec/fixtures/test_site/Gemfile
    script:
    - (cd spec/fixtures/test_site && bundle exec jekyll build --strict --trace --verbose)
    - (cd spec/fixtures/test_site && find _site -type f && echo -e '\n===\n' && cat _site/gallery_one/index.html && file _site/gallery_two/third/Morgenspaziergang-3.jpg_thumb.jpg)

# only branch-test merges to main
branches:
  only:
  - main
  - test
