---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.3
before_install: gem install bundler -v 1.17.3
jobs:
  include:
  - env: CHECK=rspec
    script:
    - bundle exec rake
  - env: CHECK=build
    gemfile: spec/fixtures/test_site/Gemfile
    install:
    - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
    script:
    - (cd spec/fixtures/test_site && bundle exec jekyll build --strict --trace && ls -la _site && cat _site/debug.html)
